CREATE TABLE app_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(120) NOT NULL,
  email VARCHAR2(120) NOT NULL UNIQUE,
  phone VARCHAR2(20),
  password_hash VARCHAR2(255) NOT NULL,
  role_code VARCHAR2(20) NOT NULL CHECK (role_code IN ('PASSENGER', 'DRIVER', 'ADMIN')),
  is_active CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE cities (
  city_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_name VARCHAR2(100) NOT NULL UNIQUE,
  state_name VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE stops (
  stop_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_id NUMBER NOT NULL,
  stop_code VARCHAR2(20) NOT NULL UNIQUE,
  stop_name VARCHAR2(120) NOT NULL,
  latitude NUMBER(10, 6) NOT NULL,
  longitude NUMBER(10, 6) NOT NULL,
  zone_name VARCHAR2(60),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_stops_city FOREIGN KEY (city_id) REFERENCES cities(city_id)
);

CREATE TABLE routes (
  route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_id NUMBER NOT NULL,
  route_code VARCHAR2(20) NOT NULL UNIQUE,
  route_name VARCHAR2(150) NOT NULL,
  mode_type VARCHAR2(20) NOT NULL CHECK (mode_type IN ('BUS', 'METRO')),
  route_status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (route_status IN ('ACTIVE', 'INACTIVE')),
  total_distance_km NUMBER(8, 2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_routes_city FOREIGN KEY (city_id) REFERENCES cities(city_id)
);

CREATE TABLE route_stops (
  route_stop_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id NUMBER NOT NULL,
  stop_id NUMBER NOT NULL,
  stop_sequence NUMBER NOT NULL,
  planned_offset_min NUMBER DEFAULT 0 NOT NULL,
  distance_from_origin_km NUMBER(8, 2),
  CONSTRAINT fk_route_stops_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT fk_route_stops_stop FOREIGN KEY (stop_id) REFERENCES stops(stop_id),
  CONSTRAINT uq_route_stop_sequence UNIQUE (route_id, stop_sequence),
  CONSTRAINT uq_route_stop_unique UNIQUE (route_id, stop_id)
);

CREATE TABLE vehicles (
  vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id NUMBER,
  vehicle_code VARCHAR2(30) NOT NULL UNIQUE,
  vehicle_type VARCHAR2(20) NOT NULL CHECK (vehicle_type IN ('BUS', 'METRO')),
  registration_no VARCHAR2(30) UNIQUE,
  total_seats NUMBER NOT NULL,
  is_ac CHAR(1) DEFAULT 'N' CHECK (is_ac IN ('Y', 'N')),
  vehicle_status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (vehicle_status IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_vehicle_route FOREIGN KEY (route_id) REFERENCES routes(route_id)
);

CREATE TABLE drivers (
  driver_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL UNIQUE,
  license_no VARCHAR2(40) NOT NULL UNIQUE,
  hire_date DATE,
  employment_status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (employment_status IN ('ACTIVE', 'LEAVE', 'INACTIVE')),
  CONSTRAINT fk_driver_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE TABLE schedules (
  schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id NUMBER NOT NULL,
  vehicle_id NUMBER,
  service_day VARCHAR2(10) NOT NULL,
  start_stop_id NUMBER NOT NULL,
  end_stop_id NUMBER NOT NULL,
  departure_time TIMESTAMP NOT NULL,
  arrival_time TIMESTAMP NOT NULL,
  frequency_min NUMBER,
  is_peak_hour CHAR(1) DEFAULT 'N' CHECK (is_peak_hour IN ('Y', 'N')),
  CONSTRAINT fk_schedule_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT fk_schedule_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
  CONSTRAINT fk_schedule_start_stop FOREIGN KEY (start_stop_id) REFERENCES stops(stop_id),
  CONSTRAINT fk_schedule_end_stop FOREIGN KEY (end_stop_id) REFERENCES stops(stop_id)
);

CREATE TABLE driver_assignments (
  assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id NUMBER NOT NULL,
  vehicle_id NUMBER NOT NULL,
  route_id NUMBER NOT NULL,
  assignment_date DATE NOT NULL,
  shift_start TIMESTAMP NOT NULL,
  shift_end TIMESTAMP,
  assignment_status VARCHAR2(20) DEFAULT 'ASSIGNED' CHECK (assignment_status IN ('ASSIGNED', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT fk_assignment_driver FOREIGN KEY (driver_id) REFERENCES drivers(driver_id),
  CONSTRAINT fk_assignment_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
  CONSTRAINT fk_assignment_route FOREIGN KEY (route_id) REFERENCES routes(route_id)
);

CREATE TABLE live_tracking (
  tracking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vehicle_id NUMBER NOT NULL,
  route_id NUMBER NOT NULL,
  current_stop_id NUMBER,
  latitude NUMBER(10, 6) NOT NULL,
  longitude NUMBER(10, 6) NOT NULL,
  speed_kmph NUMBER(6, 2) DEFAULT 0,
  delay_minutes NUMBER DEFAULT 0 NOT NULL,
  seats_available NUMBER NOT NULL,
  last_reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  delay_status VARCHAR2(20) DEFAULT 'ON_TIME' NOT NULL,
  CONSTRAINT fk_live_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
  CONSTRAINT fk_live_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT fk_live_stop FOREIGN KEY (current_stop_id) REFERENCES stops(stop_id),
  CONSTRAINT uq_live_vehicle UNIQUE (vehicle_id)
);

CREATE TABLE fares (
  fare_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id NUMBER NOT NULL,
  fare_category VARCHAR2(20) NOT NULL CHECK (fare_category IN ('ADULT', 'CHILD', 'SENIOR', 'STUDENT')),
  base_fare NUMBER(8, 2) NOT NULL,
  ac_surcharge NUMBER(8, 2) DEFAULT 0 NOT NULL,
  peak_hour_multiplier NUMBER(5, 2) DEFAULT 1 NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y', 'N')),
  CONSTRAINT fk_fare_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT uq_route_fare_category UNIQUE (route_id, fare_category)
);

CREATE TABLE pass_types (
  pass_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pass_name VARCHAR2(60) NOT NULL UNIQUE,
  duration_days NUMBER NOT NULL,
  price_amount NUMBER(8, 2) NOT NULL,
  applicable_mode VARCHAR2(20) NOT NULL CHECK (applicable_mode IN ('BUS', 'METRO', 'BOTH')),
  eligible_role VARCHAR2(20) DEFAULT 'PASSENGER'
);

CREATE TABLE passes (
  pass_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  pass_type_id NUMBER NOT NULL,
  pass_number VARCHAR2(40) NOT NULL UNIQUE,
  issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  valid_from DATE NOT NULL,
  valid_to DATE NOT NULL,
  pass_status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (pass_status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
  auto_renew CHAR(1) DEFAULT 'N' CHECK (auto_renew IN ('Y', 'N')),
  CONSTRAINT fk_pass_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_pass_type FOREIGN KEY (pass_type_id) REFERENCES pass_types(pass_type_id)
);

CREATE TABLE complaints (
  complaint_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  route_id NUMBER,
  vehicle_id NUMBER,
  complaint_category VARCHAR2(40) NOT NULL,
  complaint_text VARCHAR2(1000) NOT NULL,
  complaint_status VARCHAR2(20) DEFAULT 'PENDING' CHECK (complaint_status IN ('PENDING', 'IN_REVIEW', 'RESOLVED', 'REJECTED')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_complaint_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_complaint_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT fk_complaint_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)
);

CREATE TABLE alerts (
  alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_id NUMBER,
  vehicle_id NUMBER,
  alert_type VARCHAR2(30) NOT NULL CHECK (alert_type IN ('DELAY', 'DIVERSION', 'CANCELLATION', 'MAINTENANCE', 'INFO')),
  severity_level VARCHAR2(10) NOT NULL CHECK (severity_level IN ('LOW', 'MEDIUM', 'HIGH')),
  alert_message VARCHAR2(500) NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' CHECK (active_flag IN ('Y', 'N')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  expires_at TIMESTAMP,
  CONSTRAINT fk_alert_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT fk_alert_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id)
);

CREATE TABLE favorites (
  favorite_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  route_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_favorite_route FOREIGN KEY (route_id) REFERENCES routes(route_id),
  CONSTRAINT uq_user_favorite_route UNIQUE (user_id, route_id)
);

CREATE TABLE trip_history (
  trip_history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  origin_stop_id NUMBER NOT NULL,
  destination_stop_id NUMBER NOT NULL,
  searched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  chosen_route_id NUMBER,
  CONSTRAINT fk_trip_history_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_trip_history_origin FOREIGN KEY (origin_stop_id) REFERENCES stops(stop_id),
  CONSTRAINT fk_trip_history_destination FOREIGN KEY (destination_stop_id) REFERENCES stops(stop_id),
  CONSTRAINT fk_trip_history_route FOREIGN KEY (chosen_route_id) REFERENCES routes(route_id)
);

CREATE INDEX idx_routes_city ON routes(city_id);
CREATE INDEX idx_route_stops_route ON route_stops(route_id);
CREATE INDEX idx_live_tracking_route ON live_tracking(route_id);
CREATE INDEX idx_alerts_active ON alerts(active_flag, created_at);
CREATE INDEX idx_passes_user_status ON passes(user_id, pass_status);
CREATE INDEX idx_complaints_user_status ON complaints(user_id, complaint_status);
